CREATE TABLE IF NOT EXISTS scheduled_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    job_name VARCHAR(64)
);

COMMENT ON TABLE scheduled_jobs IS 'Root table for all scheduled jobs';
COMMENT ON COLUMN scheduled_jobs.id IS 'Surrogate identifier';
COMMENT ON COLUMN scheduled_jobs.job_name IS 'Human-readable unique job name';

CREATE TABLE IF NOT EXISTS scheduled_dates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   job_id INTEGER,
   cron_expression VARCHAR(64)
);

COMMENT ON TABLE scheduled_dates IS 'Cron-based schedule definitions';
COMMENT ON COLUMN scheduled_dates.id IS 'Surrogate identifier';
COMMENT ON COLUMN scheduled_dates.job_id IS 'FK to scheduled_jobs.id';
COMMENT ON COLUMN scheduled_dates.cron_expression IS 'Cron expression string';


CREATE TABLE IF NOT EXISTS scheduled_intervals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    job_id INTEGER,
    interval_in_millis BIGINT
);

COMMENT ON TABLE scheduled_intervals IS 'Fixed-interval schedule definitions';
COMMENT ON COLUMN scheduled_intervals.id IS 'Surrogate identifier';
COMMENT ON COLUMN scheduled_intervals.job_id IS 'FK to scheduled_jobs.id';
COMMENT ON COLUMN scheduled_intervals.interval_in_millis IS 'Interval in milliseconds';