# Generated by Django 5.2.1 on 2025-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xgbregressordatabasemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='xgbregressordatabasemodel',
            name='delay_type',
            field=models.CharField(choices=[('arrival', 'Arrival Delay'), ('departure', 'Departure Delay')], default='arrival', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xgbregressordatabasemodel',
            name='mae',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xgbregressordatabasemodel',
            name='mse',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xgbregressordatabasemodel',
            name='r2',
            field=models.FloatField(default=-100.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xgbregressordatabasemodel',
            name='rmse',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
