# Generated by Django 5.2.1 on 2025-06-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_remove_xgbregressordatabasemodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_binary', models.BinaryField()),
                ('mae', models.FloatField()),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('r2', models.FloatField()),
                ('delay_type', models.CharField(choices=[('arrival', 'Arrival Delay'), ('departure', 'Departure Delay')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='XGBRegressorDatabaseModel',
        ),
    ]
