"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path
from dotenv import load_dotenv
from spring_config import ClientConfigurationBuilder
from spring_config.client import SpringConfigClient

ENV_VAR_PATTERN = re.compile(r'^\$\{([A-Z_][A-Z0-9_]*)\}$')

load_dotenv()

print("Getting configurations from Spring Cloud config...")
config = (
    ClientConfigurationBuilder()
    .app_name("delay-predictor-service")
    .address(os.getenv("CONFIG_SERVER_URL", "http://localhost:8888"))
    .profile(os.getenv("CONFIG_PROFILE", "default"))
    .authentication((os.getenv('CONFIG_USERNAME', 'admin'), os.getenv('CONFIG_PASSWORD', 'admin')))
    .build()
)
config_client = SpringConfigClient(config)
config = config_client.get_config()


def lower_keys(d):
    if isinstance(d, dict):
        return {k.lower(): lower_keys(v) for k, v in d.items()}
    elif isinstance(d, list):
        return [lower_keys(item) for item in d]
    else:
        return d


def resolve_config_property(flat_key, config):
    keys = flat_key.lower().split('_')

    current = lower_keys(config)
    for key in keys:
        if not isinstance(current, dict) or key.lower() not in current:
            return ""
        current = current[key]

    if isinstance(current, str):
        match = ENV_VAR_PATTERN.match(current)
        if match:
            return os.getenv(match.group(1), "")
    return current


def is_training_instance() -> bool:
    val = os.getenv("IS_TRAINING_INSTANCE", "true").strip().lower()
    return val in ("1", "true", "yes", "y", "on")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'messaging.apps.MessagingConfig',
    'model.apps.ModelConfig',
    'prediction.apps.PredictionConfig',

    'django_apscheduler',
    'health_check',
    'health_check.db',
]

if is_training_instance():
    INSTALLED_APPS.append('health_check.contrib.rabbitmq')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': resolve_config_property('DB_NAME', config),
        'USER': resolve_config_property('DB_USER', config),
        'PASSWORD': resolve_config_property('DB_PASSWORD', config),
        'HOST': resolve_config_property('DB_HOST', config),
        'PORT': resolve_config_property('DB_PORT', config),
    },
    'local': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BROKER_URL = "amqp://rabbitmq:5672"


