server:
  port: 8002
  error.include-message: always
  forward-headers-strategy: framework

caching:
  delay:
    cache-duration: 24
  train-status:
    cache-duration: 24

spring:

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    database-type: postgresql
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}


  cloud:
    function:
      definition: delayInfoProcessor;weatherInfoProcessor

    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        railDataRequests-out-0:
          destination: railDataRequests
          producer:
            required-groups: auditGroup
        weatherDataRequests-out-0:
          destination: weatherDataRequests
          producer:
            required-groups: auditGroup
        delayInfoProcessor-in-0:
          destination: railDataResponses
          group: delayDataCollectorsGroup
        weatherInfoProcessor-in-0:
          destination:  weatherDataResponses
          group: delayDataCollectorsGroup

spring.cloud.stream.bindings.delayInfoProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.delayInfoProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.bindings.weatherInfoProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.weatherInfoProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.uni_obuda.thesis.railways.data.delaydatacollector

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO