app:
  messaging:
    sending:
      threadPoolSize: 24
      taskQueueSize: 750
    processing:
      threadPoolSize: 24
      taskQueueSize: 750
  data:
    processing:
      threadPoolSize: 24
      taskQueueSize: 750

server:
  port: 8002
  error.include-message: always
  forward-headers-strategy: framework

caching:
  delay:
    cache-duration: 24
  train-status:
    cache-duration: 24
  weather:
    cache-duration: 24

messaging:
  weather:
    response-event:
      wait-duration: 45
  geocoding:
    response-event:
      wait-duration: 45

spring:

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    database-type: postgresql
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    function:
      definition: delayInfoProcessor;weatherInfoProcessor;geocodingResponseProcessor;dataRequestProcessor

    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        railDataRequests-out-0:
          destination: railDataRequests
          producer:
            required-groups: auditGroup
          content-type: application/json
        weatherDataRequests-out-0:
          destination: weatherDataRequests
          producer:
            required-groups: auditGroup
          content-type: application/json
        geocodingDataRequests-out-0:
          destination: geocodingDataRequests
          producer:
            required-groups: auditGroup
          content-type: application/json
        delayInfoProcessor-in-0:
          destination: railDataResponses
          group: railDataResponsesGroup
          contentType: application/json
        weatherInfoProcessor-in-0:
          destination:  weatherDataResponses
          group: weatherDataResponsesGroup
          contentType: application/json
        geocodingResponseProcessor-in-0:
          destination: geocodingDataResponses
          group: geocodingDataResponsesGroup
          contentType: application/json
        dataRequestProcessor-in-0:
          destination: dataRequests
          group: dataRequestsGroup
          contentType: application/json
        dataRequestProcessor-out-0:
          destination: dataResponses
          producer:
            required-groups: auditGroup
          contentType: application/json

spring.cloud.stream.bindings.delayInfoProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.delayInfoProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.bindings.weatherInfoProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.weatherInfoProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.bindings.geocodingResponseProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.geocodingResponseProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.rabbit.bindings.dataRequestProcessor-in-0.consumer:
  atoBindDlg: true
  republishToDlq: true

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.uni_obuda.thesis.railways.data.delaydatacollector

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO

---
spring.activate.on-profile: docker

server.port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://postgresql-1:5432/${POSTGRES_DB_NAME}
  flyway:
    url: jdbc:postgresql://postgresql-1:5432/${POSTGRES_DB_NAME}
  data:
    redis:
      host: redis-1
      port: 6379

