app:
  threadPoolSize: 4
  taskQueueSize: 250

server:
  port: 8003
  error.include-message: always
  forward-headers-strategy: framework

maps.api:
  base-url: https://maps.googleapis.com/maps/api
  geocoding-url: /geocode/json
  country-code : Hungary
  api-key: '{cipher}c0c007c88f39d04e53d2d9266e6eae4be464c5cc88ee3ff9d2fe164099df17f0f838e82e0bdf2ef1145df81d0c7e46e45ef9b1f537f6d03fc920a8f71d172002'

tcp:
  connection:
    timeout-in-ms: 15000
    read:
      timeout-in-ms: 15000
    write:
      timeout-in-ms: 15000

resilience4j:
  circuitbreaker:
    instances:
      geocodingApi:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.InternalApiException
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiFormatMismatchException

  retry:
    instances:
      geocodingApi:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiException
          - org.springframework.web.reactive.function.client.WebClientRequestException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.InternalApiException
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiFormatMismatchException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted

  ratelimiter:
    instances:
      geocodingApi:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s

spring:

  cloud:
    function:
      definition: messageProcessor

    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        geocodingDataResponses-out-0:
          destination: geocodingDataResponses
          producer:
            required-groups: auditGroup
        messageProcessor-in-0:
          destination: geocodingDataRequests
          group: geocodingDataRequestsGroup
          contentType: application/json

    rabbit:
      bindings:
        geocodingDataResponses-out-0:
          producer:
            lazy: true
            maxLength: 100
            overflowBehavior: drop-head

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.uni_obuda.thesis.railways.data.geocodingservice

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    reactor.netty: INFO
    reactor.netty.resources: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    org.springframework.web.reactive.function.client.ExchangeFilterFunctions: DEBUG
    org.springframework.web.reactive.function.client.WebClient: INFO

---
spring.activate.on-profile: docker

server.port: 8080

---
spring.activate.on-profile: instance-1

spring.cloud.stream.bindings.messageProcessor-in-0:
  destination: geocodingDataRequests
  group: geocodingDataRequestsGroup
  consumer:
    partitioned: true
    instance-index: 0

---
spring.activate.on-profile: instance-2

spring.cloud.stream.bindings.messageProcessor-in-0:
  destination: geocodingDataRequests
  group: geocodingDataRequestsGroup
  consumer:
    partitioned: true
    instance-index: 1

---
spring.activate.on-profile: instance-3

spring.cloud.stream.bindings.messageProcessor-in-0:
  destination: geocodingDataRequests
  group: geocodingDataRequestsGroup
  consumer:
    partitioned: true
    instance-index: 2
