app:
  threadPoolSize: 24
  taskQueueSize: 750


server:
  port: 8000
  error.include-message: always
  forward-headers-strategy: framework

railway.api:
  base-url: http://apiv2.oroszi.net/elvira
  timetable-getter-uri: /
  train-details-getter-uri: /details

tcp:
    connection:
      timeout-in-ms: 30000
      read:
        timeout-in-ms: 30000
      write:
        timeout-in-ms: 30000

resilience4j:
  circuitbreaker:
    instances:
      getTimetableApi:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.InternalApiException
      getTrainDetailsApi:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.InternalApiException

  retry:
    instances:
      getTimetableApi:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - org.springframework.web.reactive.function.client.WebClientRequestException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
      getTrainDetailsApi:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - org.springframework.web.reactive.function.client.WebClientRequestException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6380

  cloud:
    function:
      definition: messageProcessor

    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        railDataResponses-out-0:
          destination: railDataResponses
          producer:
            required-groups: auditGroup, delayDataCollectorsGroup
        messageProcessor-in-0:
          destination: railDataRequests
          group: railDataCollectorsGroup
          contentType: application/json


  spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
    maxAttempts: 3
    backOffInitialInterval: 500
    backOffMaxInterval: 1000
    backOffMultiplier: 2.0

  spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
    autoBindDlq: true
    republishToDlq: true

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.uni_obuda.thesis.railways.data.raildatacollector

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    reactor.netty: INFO
    reactor.netty.resources: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    org.springframework.web.reactive.function.client.ExchangeFilterFunctions: DEBUG
    org.springframework.web.reactive.function.client.WebClient: INFO
