server:
  port: 9999
  error.include-message: always
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}

role:
  default.name: ROLE_USER
  admin.name: ROLE_ADMIN

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    database-type: postgresql
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO

---
spring.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
  flyway:
    url: jdbc:postgresql://postgresql-3:5432/${POSTGRES_DB_NAME}
