app:
  threadPoolSize: 8
  taskQueueSize: 500

server:
  port: 8001
  error.include-message: always
  forward-headers-strategy: framework

weather.api:
  base-url: https://api.open-meteo.com
  forecast-url: /v1/forecast
  time-zone: Europe/Berlin

tcp:
  connection:
    timeout-in-ms: 15000
    read:
      timeout-in-ms: 15000
    write:
      timeout-in-ms: 15000

resilience4j:
  circuitbreaker:
    instances:
      getWeatherDataApi:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        ignoreExceptions:
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiException
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiFormatMismatchException


  retry:
    instances:
      getWeatherDataApi:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiException
          - hu.uni_obuda.thesis.railways.util.exception.datacollectors.ExternalApiFormatMismatchException
        ignoreExceptions:
          - io.github.resilience4j.ratelimiter.RequestNotPermitted

  ratelimiter:
    instances:
      getWeatherDataApi:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 3s

spring:

  cloud:
    function:
      definition: messageProcessor

    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        weatherDataResponses-out-0:
          destination: weatherDataResponses
          producer:
            required-groups: auditGroup
        messageProcessor-in-0:
          destination: weatherDataRequests
          group: weatherDataRequestsGroup
          contentType: application/json

    rabbit:
      bindings:
        weatherDataResponses-out-0:
          producer:
            lazy: true
            maxLength: 100
            overflowBehavior: drop-head

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.uni_obuda.thesis.railways.data.weatherdatacollector

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    reactor.netty: INFO
    reactor.netty.resources: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    org.springframework.web.reactive.function.client.ExchangeFilterFunctions: DEBUG
    org.springframework.web.reactive.function.client.WebClient: INFO

---
spring.config.activate.on-profile: docker

server.port: 8080

---
spring.config.activate.on-profile: instance-1

spring.cloud.stream.bindings.messageProcessor-in-0:
  destination: weatherDataRequests
  group: weatherDataRequestsGroup
  consumer:
    partitioned: true
    instance-index: 0

---
spring.config.activate.on-profile: instance-2

spring.cloud.stream.bindings.messageProcessor-in-0:
  destination: weatherDataRequests
  group: weatherDataRequestsGroup
  consumer:
    partitioned: true
    instance-index: 1

---
spring.config.activate.on-profile: instance-3

spring.cloud.stream.bindings.messageProcessor-in-0:
  destination: weatherDataRequests
  group: weatherDataRequestsGroup
  consumer:
    partitioned: true
    instance-index: 2